-- Sinh tự động từ src/data/db/schema.py – KHÔNG sửa tay. Hệ quản trị: postgresql

CREATE TABLE app_settings (
	key VARCHAR(50) NOT NULL, 
	value TEXT NOT NULL, 
	note TEXT, 
	CONSTRAINT pk_app_settings PRIMARY KEY (key)
);


-- data_sources: Văn bản/nguồn mà dữ liệu được lấy ra; mọi dữ liệu tham chiếu đều truy được về đây
CREATE TABLE data_sources (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	code VARCHAR(50) NOT NULL, 
	title TEXT NOT NULL, 
	document_number VARCHAR(50), 
	issued_date DATE, 
	issuer TEXT, 
	file_name TEXT, 
	note TEXT, 
	CONSTRAINT pk_data_sources PRIMARY KEY (id), 
	CONSTRAINT uq_data_sources_code UNIQUE (code)
);


-- skills: Kỹ năng mà học phần rèn luyện (danh mục do nhóm tự gán)
CREATE TABLE skills (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	code VARCHAR(50) NOT NULL, 
	name TEXT NOT NULL, 
	CONSTRAINT pk_skills PRIMARY KEY (id), 
	CONSTRAINT uq_skills_code UNIQUE (code)
);


-- topics: Chủ đề học phần; dùng để nhóm các môn liên quan và cho sinh viên khai sở thích
CREATE TABLE topics (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	code VARCHAR(50) NOT NULL, 
	name TEXT NOT NULL, 
	CONSTRAINT pk_topics PRIMARY KEY (id), 
	CONSTRAINT uq_topics_code UNIQUE (code)
);


-- universities: Trường đại học. Mỗi trường độc lập: có ngành, học phần, thang điểm, lịch học kỳ riêng
CREATE TABLE universities (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	code VARCHAR(20) NOT NULL, 
	name TEXT NOT NULL, 
	name_en TEXT, 
	short_name VARCHAR(50), 
	is_demo BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT pk_universities PRIMARY KEY (id), 
	CONSTRAINT uq_universities_code UNIQUE (code)
);


CREATE TABLE academic_years (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	university_id INTEGER NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	start_year INTEGER NOT NULL, 
	CONSTRAINT pk_academic_years PRIMARY KEY (id), 
	CONSTRAINT uq_academic_years_university_id_code UNIQUE (university_id, code), 
	CONSTRAINT fk_academic_years_university_id_universities FOREIGN KEY(university_id) REFERENCES universities (id) ON DELETE RESTRICT
);

CREATE INDEX ix_academic_years_university_id ON academic_years (university_id);

-- courses: Học phần của một trường, dùng chung cho mọi CTĐT của trường đó
CREATE TABLE courses (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	university_id INTEGER NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	name TEXT NOT NULL, 
	name_en TEXT, 
	credits INTEGER NOT NULL, 
	lecture_hours INTEGER, 
	practice_hours INTEGER, 
	self_study_hours INTEGER, 
	teaching_language VARCHAR(5) DEFAULT 'vi' NOT NULL, 
	CONSTRAINT pk_courses PRIMARY KEY (id), 
	CONSTRAINT uq_courses_university_id_code UNIQUE (university_id, code), 
	CONSTRAINT ck_courses_credits CHECK (credits > 0), 
	CONSTRAINT fk_courses_university_id_universities FOREIGN KEY(university_id) REFERENCES universities (id) ON DELETE RESTRICT
);

CREATE INDEX ix_courses_university_id ON courses (university_id);

-- data_issues: Chỗ văn bản gốc mâu thuẫn hoặc thiếu; ghi lại thay vì âm thầm sửa
CREATE TABLE data_issues (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	source_id INTEGER NOT NULL, 
	entity_type VARCHAR(50) NOT NULL, 
	entity_key VARCHAR(100) NOT NULL, 
	issue_type VARCHAR(50) NOT NULL, 
	description TEXT NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	CONSTRAINT pk_data_issues PRIMARY KEY (id), 
	CONSTRAINT ck_data_issues_status CHECK (status IN ('open', 'resolved_in_data', 'closed')), 
	CONSTRAINT fk_data_issues_source_id_data_sources FOREIGN KEY(source_id) REFERENCES data_sources (id) ON DELETE RESTRICT
);

CREATE INDEX ix_data_issues_source_id ON data_issues (source_id);

CREATE TABLE faculties (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	university_id INTEGER NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	name TEXT NOT NULL, 
	name_en TEXT, 
	CONSTRAINT pk_faculties PRIMARY KEY (id), 
	CONSTRAINT uq_faculties_university_id_code UNIQUE (university_id, code), 
	CONSTRAINT fk_faculties_university_id_universities FOREIGN KEY(university_id) REFERENCES universities (id) ON DELETE RESTRICT
);

CREATE INDEX ix_faculties_university_id ON faculties (university_id);

CREATE TABLE grading_schemes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	university_id INTEGER NOT NULL, 
	code VARCHAR(30) NOT NULL, 
	name TEXT NOT NULL, 
	max_score NUMERIC(4, 2) NOT NULL, 
	pass_score NUMERIC(4, 2) NOT NULL, 
	source_id INTEGER, 
	CONSTRAINT pk_grading_schemes PRIMARY KEY (id), 
	CONSTRAINT ck_grading_schemes_pass_score CHECK (pass_score > 0 AND pass_score <= max_score), 
	CONSTRAINT fk_grading_schemes_university_id_universities FOREIGN KEY(university_id) REFERENCES universities (id) ON DELETE RESTRICT, 
	CONSTRAINT uq_grading_schemes_code UNIQUE (code), 
	CONSTRAINT fk_grading_schemes_source_id_data_sources FOREIGN KEY(source_id) REFERENCES data_sources (id) ON DELETE RESTRICT
);

CREATE INDEX ix_grading_schemes_source_id ON grading_schemes (source_id);
CREATE INDEX ix_grading_schemes_university_id ON grading_schemes (university_id);

-- students: Sinh viên. Khóa là id; (university_id, student_code) là khóa nghiệp vụ
CREATE TABLE students (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	university_id INTEGER NOT NULL, 
	student_code VARCHAR(30) NOT NULL, 
	full_name TEXT NOT NULL, 
	date_of_birth DATE, 
	email TEXT, 
	is_synthetic BOOLEAN DEFAULT false NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_students PRIMARY KEY (id), 
	CONSTRAINT uq_students_university_id_student_code UNIQUE (university_id, student_code), 
	CONSTRAINT fk_students_university_id_universities FOREIGN KEY(university_id) REFERENCES universities (id) ON DELETE RESTRICT
);

CREATE INDEX ix_students_university_id ON students (university_id);

-- course_equivalences: Học phần tương đương/thay thế
CREATE TABLE course_equivalences (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	course_id INTEGER NOT NULL, 
	equivalent_course_id INTEGER NOT NULL, 
	source_id INTEGER, 
	note TEXT, 
	CONSTRAINT pk_course_equivalences PRIMARY KEY (id), 
	CONSTRAINT uq_course_equivalences_course_id_equivalent_course_id UNIQUE (course_id, equivalent_course_id), 
	CONSTRAINT ck_course_equivalences_not_self CHECK (course_id <> equivalent_course_id), 
	CONSTRAINT fk_course_equivalences_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_course_equivalences_equivalent_course_id_courses FOREIGN KEY(equivalent_course_id) REFERENCES courses (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_course_equivalences_source_id_data_sources FOREIGN KEY(source_id) REFERENCES data_sources (id) ON DELETE RESTRICT
);

CREATE INDEX ix_course_equivalences_course_id ON course_equivalences (course_id);
CREATE INDEX ix_course_equivalences_equivalent_course_id ON course_equivalences (equivalent_course_id);
CREATE INDEX ix_course_equivalences_source_id ON course_equivalences (source_id);

-- course_skills: Học phần rèn kỹ năng nào, mức độ (weight)
CREATE TABLE course_skills (
	course_id INTEGER NOT NULL, 
	skill_id INTEGER NOT NULL, 
	weight NUMERIC(4, 2) DEFAULT '1' NOT NULL, 
	CONSTRAINT pk_course_skills PRIMARY KEY (course_id, skill_id), 
	CONSTRAINT ck_course_skills_weight CHECK (weight > 0), 
	CONSTRAINT fk_course_skills_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE CASCADE, 
	CONSTRAINT fk_course_skills_skill_id_skills FOREIGN KEY(skill_id) REFERENCES skills (id)
);

CREATE INDEX ix_course_skills_skill_id ON course_skills (skill_id);

-- course_topics: Học phần thuộc chủ đề nào; mỗi học phần có đúng một chủ đề chính
CREATE TABLE course_topics (
	course_id INTEGER NOT NULL, 
	topic_id INTEGER NOT NULL, 
	is_primary BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT pk_course_topics PRIMARY KEY (course_id, topic_id), 
	CONSTRAINT fk_course_topics_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE CASCADE, 
	CONSTRAINT fk_course_topics_topic_id_topics FOREIGN KEY(topic_id) REFERENCES topics (id)
);

CREATE INDEX ix_course_topics_topic_id ON course_topics (topic_id);
CREATE UNIQUE INDEX uq_course_topics_one_primary ON course_topics (course_id) WHERE is_primary;

CREATE TABLE grade_conversions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	grading_scheme_id INTEGER NOT NULL, 
	letter VARCHAR(3) NOT NULL, 
	min_score NUMERIC(4, 2) NOT NULL, 
	max_score NUMERIC(4, 2) NOT NULL, 
	grade_point NUMERIC(3, 2) NOT NULL, 
	is_pass BOOLEAN NOT NULL, 
	CONSTRAINT pk_grade_conversions PRIMARY KEY (id), 
	CONSTRAINT uq_grade_conversions_grading_scheme_id_letter UNIQUE (grading_scheme_id, letter), 
	CONSTRAINT ck_grade_conversions_range CHECK (min_score <= max_score), 
	CONSTRAINT fk_grade_conversions_grading_scheme_id_grading_schemes FOREIGN KEY(grading_scheme_id) REFERENCES grading_schemes (id) ON DELETE CASCADE
);

CREATE INDEX ix_grade_conversions_grading_scheme_id ON grade_conversions (grading_scheme_id);

-- majors: Ngành đào tạo của một trường
CREATE TABLE majors (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	university_id INTEGER NOT NULL, 
	faculty_id INTEGER, 
	code VARCHAR(20) NOT NULL, 
	name TEXT NOT NULL, 
	name_en TEXT, 
	degree_level VARCHAR(20) NOT NULL, 
	is_pilot BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT pk_majors PRIMARY KEY (id), 
	CONSTRAINT uq_majors_university_id_code UNIQUE (university_id, code), 
	CONSTRAINT ck_majors_degree_level CHECK (degree_level IN ('bachelor', 'engineer', 'master', 'doctor')), 
	CONSTRAINT fk_majors_university_id_universities FOREIGN KEY(university_id) REFERENCES universities (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_majors_faculty_id_faculties FOREIGN KEY(faculty_id) REFERENCES faculties (id) ON DELETE RESTRICT
);

CREATE INDEX ix_majors_faculty_id ON majors (faculty_id);
CREATE INDEX ix_majors_university_id ON majors (university_id);

-- student_attributes: DỮ LIỆU NHẠY CẢM, chỉ dùng để đánh giá công bằng; thuật toán gợi ý KHÔNG được đọc
CREATE TABLE student_attributes (
	student_id INTEGER NOT NULL, 
	attribute_code VARCHAR(30) NOT NULL, 
	value TEXT NOT NULL, 
	CONSTRAINT pk_student_attributes PRIMARY KEY (student_id, attribute_code), 
	CONSTRAINT fk_student_attributes_student_id_students FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE CASCADE
);


-- student_interests: Chủ đề sinh viên tự khai là thích – tín hiệu PHỤ; tín hiệu chính là kết quả học tập
CREATE TABLE student_interests (
	student_id INTEGER NOT NULL, 
	topic_id INTEGER NOT NULL, 
	weight NUMERIC(4, 2) DEFAULT '1' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_student_interests PRIMARY KEY (student_id, topic_id), 
	CONSTRAINT ck_student_interests_weight CHECK (weight > 0 AND weight <= 1), 
	CONSTRAINT fk_student_interests_student_id_students FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE CASCADE, 
	CONSTRAINT fk_student_interests_topic_id_topics FOREIGN KEY(topic_id) REFERENCES topics (id)
);

CREATE INDEX ix_student_interests_topic_id ON student_interests (topic_id);

CREATE TABLE terms (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	university_id INTEGER NOT NULL, 
	academic_year_id INTEGER NOT NULL, 
	code VARCHAR(10) NOT NULL, 
	term_no INTEGER NOT NULL, 
	name TEXT NOT NULL, 
	start_date DATE, 
	end_date DATE, 
	CONSTRAINT pk_terms PRIMARY KEY (id), 
	CONSTRAINT uq_terms_university_id_code UNIQUE (university_id, code), 
	CONSTRAINT ck_terms_term_no CHECK (term_no IN (1, 2, 3)), 
	CONSTRAINT fk_terms_university_id_universities FOREIGN KEY(university_id) REFERENCES universities (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_terms_academic_year_id_academic_years FOREIGN KEY(academic_year_id) REFERENCES academic_years (id) ON DELETE RESTRICT
);

CREATE INDEX ix_terms_academic_year_id ON terms (academic_year_id);
CREATE INDEX ix_terms_university_id ON terms (university_id);

-- course_registrations: Đăng ký học phần (với dữ liệu tự tạo: đáp án để đo độ chính xác gợi ý)
CREATE TABLE course_registrations (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	student_id INTEGER NOT NULL, 
	course_id INTEGER NOT NULL, 
	term_id INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	source VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_course_registrations PRIMARY KEY (id), 
	CONSTRAINT uq_course_registrations_student_id_course_id_term_id UNIQUE (student_id, course_id, term_id), 
	CONSTRAINT ck_course_registrations_status CHECK (status IN ('planned', 'registered', 'dropped')), 
	CONSTRAINT ck_course_registrations_source CHECK (source IN ('student', 'simulated', 'imported')), 
	CONSTRAINT fk_course_registrations_student_id_students FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE CASCADE, 
	CONSTRAINT fk_course_registrations_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_course_registrations_term_id_terms FOREIGN KEY(term_id) REFERENCES terms (id) ON DELETE RESTRICT
);

CREATE INDEX ix_course_registrations_course_id ON course_registrations (course_id);
CREATE INDEX ix_course_registrations_student_id ON course_registrations (student_id);
CREATE INDEX ix_course_registrations_term_id ON course_registrations (term_id);

-- course_results: Kết quả học tập: mỗi dòng là một lần học một học phần
CREATE TABLE course_results (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	student_id INTEGER NOT NULL, 
	course_id INTEGER NOT NULL, 
	term_id INTEGER NOT NULL, 
	attempt_no INTEGER DEFAULT '1' NOT NULL, 
	score NUMERIC(4, 2), 
	letter_grade VARCHAR(3), 
	grade_point NUMERIC(3, 2), 
	status VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_course_results PRIMARY KEY (id), 
	CONSTRAINT uq_course_results_student_id_course_id_term_id UNIQUE (student_id, course_id, term_id), 
	CONSTRAINT ck_course_results_status CHECK (status IN ('passed', 'failed', 'exempted', 'withdrawn', 'in_progress')), 
	CONSTRAINT ck_course_results_score_required CHECK (status IN ('exempted', 'withdrawn', 'in_progress') OR score IS NOT NULL), 
	CONSTRAINT ck_course_results_score_non_negative CHECK (score IS NULL OR score >= 0), 
	CONSTRAINT fk_course_results_student_id_students FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE CASCADE, 
	CONSTRAINT fk_course_results_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_course_results_term_id_terms FOREIGN KEY(term_id) REFERENCES terms (id) ON DELETE RESTRICT
);

CREATE INDEX ix_course_results_course_id ON course_results (course_id);
CREATE INDEX ix_course_results_student_course ON course_results (student_id, course_id);
CREATE INDEX ix_course_results_student_id ON course_results (student_id);
CREATE INDEX ix_course_results_term_id ON course_results (term_id);

-- curricula: Khung chương trình đào tạo: một phiên bản của một ngành, áp dụng cho một dải khóa
CREATE TABLE curricula (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	code VARCHAR(50) NOT NULL, 
	major_id INTEGER NOT NULL, 
	name TEXT NOT NULL, 
	name_en TEXT, 
	program_type VARCHAR(30) NOT NULL, 
	effective_from_cohort INTEGER NOT NULL, 
	effective_to_cohort INTEGER, 
	total_credits INTEGER NOT NULL, 
	standard_semesters INTEGER NOT NULL, 
	max_credits_per_term INTEGER NOT NULL, 
	grading_scheme_id INTEGER NOT NULL, 
	source_id INTEGER, 
	status VARCHAR(20) NOT NULL, 
	CONSTRAINT pk_curricula PRIMARY KEY (id), 
	CONSTRAINT ck_curricula_status CHECK (status IN ('draft', 'active', 'retired')), 
	CONSTRAINT ck_curricula_positive CHECK (total_credits > 0 AND standard_semesters > 0), 
	CONSTRAINT ck_curricula_cohort_range CHECK (effective_to_cohort IS NULL OR effective_to_cohort >= effective_from_cohort), 
	CONSTRAINT uq_curricula_code UNIQUE (code), 
	CONSTRAINT fk_curricula_major_id_majors FOREIGN KEY(major_id) REFERENCES majors (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_curricula_grading_scheme_id_grading_schemes FOREIGN KEY(grading_scheme_id) REFERENCES grading_schemes (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_curricula_source_id_data_sources FOREIGN KEY(source_id) REFERENCES data_sources (id) ON DELETE RESTRICT
);

CREATE INDEX ix_curricula_grading_scheme_id ON curricula (grading_scheme_id);
CREATE INDEX ix_curricula_major_id ON curricula (major_id);
CREATE INDEX ix_curricula_source_id ON curricula (source_id);

-- curriculum_blocks: Khối kiến thức (cây). Nhóm tự chọn là khối có selection_rule = choose_credits
CREATE TABLE curriculum_blocks (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	curriculum_id INTEGER NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	parent_block_id INTEGER, 
	name TEXT NOT NULL, 
	selection_rule VARCHAR(20) NOT NULL, 
	required_credits INTEGER NOT NULL, 
	counts_toward_total BOOLEAN DEFAULT true NOT NULL, 
	sort_order INTEGER NOT NULL, 
	note TEXT, 
	CONSTRAINT pk_curriculum_blocks PRIMARY KEY (id), 
	CONSTRAINT uq_curriculum_blocks_curriculum_id_code UNIQUE (curriculum_id, code), 
	CONSTRAINT ck_curriculum_blocks_selection_rule CHECK (selection_rule IN ('all', 'choose_credits', 'container')), 
	CONSTRAINT fk_curriculum_blocks_curriculum_id_curricula FOREIGN KEY(curriculum_id) REFERENCES curricula (id) ON DELETE CASCADE, 
	CONSTRAINT fk_curriculum_blocks_parent_block_id_curriculum_blocks FOREIGN KEY(parent_block_id) REFERENCES curriculum_blocks (id) ON DELETE RESTRICT
);

CREATE INDEX ix_curriculum_blocks_curriculum_id ON curriculum_blocks (curriculum_id);
CREATE INDEX ix_curriculum_blocks_parent_block_id ON curriculum_blocks (parent_block_id);

-- student_programs: Sinh viên theo học CTĐT nào (cho phép chuyển ngành, học song ngành)
CREATE TABLE student_programs (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	student_id INTEGER NOT NULL, 
	curriculum_id INTEGER NOT NULL, 
	cohort_year INTEGER NOT NULL, 
	admission_term_id INTEGER, 
	status VARCHAR(20) NOT NULL, 
	is_primary BOOLEAN DEFAULT true NOT NULL, 
	start_date DATE, 
	end_date DATE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_student_programs PRIMARY KEY (id), 
	CONSTRAINT uq_student_programs_student_id_curriculum_id UNIQUE (student_id, curriculum_id), 
	CONSTRAINT ck_student_programs_status CHECK (status IN ('active', 'graduated', 'suspended', 'withdrawn', 'transferred')), 
	CONSTRAINT ck_student_programs_date_range CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date), 
	CONSTRAINT fk_student_programs_student_id_students FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE CASCADE, 
	CONSTRAINT fk_student_programs_curriculum_id_curricula FOREIGN KEY(curriculum_id) REFERENCES curricula (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_student_programs_admission_term_id_terms FOREIGN KEY(admission_term_id) REFERENCES terms (id) ON DELETE RESTRICT
);

CREATE INDEX ix_student_programs_admission_term_id ON student_programs (admission_term_id);
CREATE INDEX ix_student_programs_curriculum_id ON student_programs (curriculum_id);
CREATE INDEX ix_student_programs_student_id ON student_programs (student_id);
CREATE UNIQUE INDEX uq_student_programs_one_primary ON student_programs (student_id) WHERE is_primary;

-- curriculum_courses: Học phần thuộc khung nào, nằm trong khối nào
CREATE TABLE curriculum_courses (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	curriculum_id INTEGER NOT NULL, 
	block_id INTEGER NOT NULL, 
	course_id INTEGER NOT NULL, 
	sort_no INTEGER, 
	recommended_semester INTEGER, 
	recommended_semester_source_id INTEGER, 
	note TEXT, 
	CONSTRAINT pk_curriculum_courses PRIMARY KEY (id), 
	CONSTRAINT uq_curriculum_courses_curriculum_id_course_id UNIQUE (curriculum_id, course_id), 
	CONSTRAINT ck_curriculum_courses_semester CHECK (recommended_semester IS NULL OR recommended_semester >= 1), 
	CONSTRAINT fk_curriculum_courses_curriculum_id_curricula FOREIGN KEY(curriculum_id) REFERENCES curricula (id) ON DELETE CASCADE, 
	CONSTRAINT fk_curriculum_courses_block_id_curriculum_blocks FOREIGN KEY(block_id) REFERENCES curriculum_blocks (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_curriculum_courses_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_curriculum_courses_recommended_semester_source_id_da_7555 FOREIGN KEY(recommended_semester_source_id) REFERENCES data_sources (id) ON DELETE RESTRICT
);

CREATE INDEX ix_curriculum_courses_block_id ON curriculum_courses (block_id);
CREATE INDEX ix_curriculum_courses_course_id ON curriculum_courses (course_id);
CREATE INDEX ix_curriculum_courses_curriculum_id ON curriculum_courses (curriculum_id);
CREATE INDEX ix_curriculum_courses_recommended_semester_source_id ON curriculum_courses (recommended_semester_source_id);

CREATE TABLE recommendation_runs (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	student_id INTEGER NOT NULL, 
	student_program_id INTEGER NOT NULL, 
	term_id INTEGER NOT NULL, 
	algorithm VARCHAR(50) NOT NULL, 
	algorithm_version VARCHAR(20) NOT NULL, 
	parameters JSONB, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_recommendation_runs PRIMARY KEY (id), 
	CONSTRAINT fk_recommendation_runs_student_id_students FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE CASCADE, 
	CONSTRAINT fk_recommendation_runs_student_program_id_student_programs FOREIGN KEY(student_program_id) REFERENCES student_programs (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_recommendation_runs_term_id_terms FOREIGN KEY(term_id) REFERENCES terms (id) ON DELETE RESTRICT
);

CREATE INDEX ix_recommendation_runs_student_id ON recommendation_runs (student_id);
CREATE INDEX ix_recommendation_runs_student_program_id ON recommendation_runs (student_program_id);
CREATE INDEX ix_recommendation_runs_term_id ON recommendation_runs (term_id);

-- prerequisites: Điều kiện của học phần TRONG một CTĐT (mỗi văn bản tự quy định)
CREATE TABLE prerequisites (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	curriculum_course_id INTEGER NOT NULL, 
	group_no INTEGER NOT NULL, 
	required_course_code VARCHAR(20) NOT NULL, 
	required_course_id INTEGER, 
	requirement_type VARCHAR(20) DEFAULT 'prerequisite' NOT NULL, 
	min_score NUMERIC(4, 2), 
	CONSTRAINT pk_prerequisites PRIMARY KEY (id), 
	CONSTRAINT uq_prerequisites_curriculum_course_id_group_no_required_12b8 UNIQUE (curriculum_course_id, group_no, required_course_code), 
	CONSTRAINT ck_prerequisites_requirement_type CHECK (requirement_type IN ('prerequisite', 'prior', 'corequisite')), 
	CONSTRAINT fk_prerequisites_curriculum_course_id_curriculum_courses FOREIGN KEY(curriculum_course_id) REFERENCES curriculum_courses (id) ON DELETE CASCADE, 
	CONSTRAINT fk_prerequisites_required_course_id_courses FOREIGN KEY(required_course_id) REFERENCES courses (id) ON DELETE RESTRICT
);

CREATE INDEX ix_prerequisites_curriculum_course_id ON prerequisites (curriculum_course_id);
CREATE INDEX ix_prerequisites_required_course_id ON prerequisites (required_course_id);

CREATE TABLE recommendation_items (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	run_id INTEGER NOT NULL, 
	course_id INTEGER NOT NULL, 
	rank INTEGER NOT NULL, 
	score NUMERIC(8, 4) NOT NULL, 
	explanation JSONB, 
	CONSTRAINT pk_recommendation_items PRIMARY KEY (id), 
	CONSTRAINT uq_recommendation_items_run_id_rank UNIQUE (run_id, rank), 
	CONSTRAINT fk_recommendation_items_run_id_recommendation_runs FOREIGN KEY(run_id) REFERENCES recommendation_runs (id) ON DELETE CASCADE, 
	CONSTRAINT fk_recommendation_items_course_id_courses FOREIGN KEY(course_id) REFERENCES courses (id) ON DELETE RESTRICT
);

CREATE INDEX ix_recommendation_items_course_id ON recommendation_items (course_id);
CREATE INDEX ix_recommendation_items_run_id ON recommendation_items (run_id);

CREATE TABLE recommendation_feedback (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	item_id INTEGER NOT NULL, 
	action VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT pk_recommendation_feedback PRIMARY KEY (id), 
	CONSTRAINT ck_recommendation_feedback_action CHECK (action IN ('viewed', 'accepted', 'rejected', 'registered')), 
	CONSTRAINT fk_recommendation_feedback_item_id_recommendation_items FOREIGN KEY(item_id) REFERENCES recommendation_items (id) ON DELETE CASCADE
);

CREATE INDEX ix_recommendation_feedback_item_id ON recommendation_feedback (item_id);

CREATE VIEW v_curriculum_courses AS
        SELECT cu.id AS curriculum_id, cu.code AS curriculum_code, u.code AS university_code,
               c.id AS course_id, c.code AS course_code, c.name AS course_name, c.name_en AS course_name_en,
               c.credits, c.teaching_language,
               b.id AS block_id, b.code AS block_code, b.name AS block_name, b.selection_rule,
               CASE WHEN b.selection_rule = 'all' THEN 1 ELSE 0 END AS is_required,
               b.required_credits AS block_required_credits,
               CASE WHEN b.counts_toward_total THEN 1 ELSE 0 END AS counts_toward_total,
               cc.recommended_semester, (cc.recommended_semester + 1) / 2 AS recommended_year, cc.sort_no
        FROM curriculum_courses cc
        JOIN curricula cu ON cu.id = cc.curriculum_id
        JOIN majors m ON m.id = cu.major_id
        JOIN universities u ON u.id = m.university_id
        JOIN courses c ON c.id = cc.course_id
        JOIN curriculum_blocks b ON b.id = cc.block_id;

CREATE VIEW v_prerequisites AS
        SELECT cc.curriculum_id, c.code AS course_code, p.group_no, p.required_course_code, p.requirement_type,
               p.min_score,
               CASE WHEN EXISTS (SELECT 1 FROM curriculum_courses x
                                 WHERE x.curriculum_id = cc.curriculum_id AND x.course_id = p.required_course_id)
                    THEN 1 ELSE 0 END AS in_curriculum
        FROM prerequisites p
        JOIN curriculum_courses cc ON cc.id = p.curriculum_course_id
        JOIN courses c ON c.id = cc.course_id;

CREATE VIEW v_student_programs AS
        SELECT s.id AS student_id, u.code AS university_code, s.student_code, s.full_name, s.is_synthetic,
               sp.id AS student_program_id, cu.id AS curriculum_id, cu.code AS curriculum_code,
               m.code AS major_code, m.name AS major_name, sp.cohort_year, sp.status, sp.is_primary
        FROM students s
        JOIN universities u ON u.id = s.university_id
        JOIN student_programs sp ON sp.student_id = s.id
        JOIN curricula cu ON cu.id = sp.curriculum_id
        JOIN majors m ON m.id = cu.major_id;

CREATE VIEW v_course_results AS
        SELECT r.id AS result_id, r.student_id, c.code AS course_code, r.course_id, t.code AS term_code,
               r.attempt_no, r.score, r.letter_grade, r.grade_point, r.status,
               ROW_NUMBER() OVER (PARTITION BY r.student_id, r.course_id
                                  ORDER BY t.code DESC, r.attempt_no DESC) AS recency
        FROM course_results r
        JOIN courses c ON c.id = r.course_id
        JOIN terms t ON t.id = r.term_id;

CREATE VIEW v_student_progress AS
        SELECT sp.student_id, sp.id AS student_program_id,
               COALESCE(SUM(c.credits) FILTER (WHERE r.status IN ('passed', 'exempted') AND b.counts_toward_total), 0)
                   AS credits_earned,
               COALESCE(SUM(c.credits) FILTER (WHERE r.status = 'failed' AND b.counts_toward_total), 0)
                   AS credits_outstanding,
               ROUND(SUM(r.grade_point * c.credits) FILTER (WHERE r.status IN ('passed', 'failed') AND b.counts_toward_total)
                     / NULLIF(SUM(c.credits) FILTER (WHERE r.status IN ('passed', 'failed') AND b.counts_toward_total), 0), 2)
                   AS gpa,
               COUNT(DISTINCT r.term_code) AS terms_studied
        FROM student_programs sp
        LEFT JOIN v_course_results r ON r.student_id = sp.student_id AND r.recency = 1
        LEFT JOIN courses c ON c.id = r.course_id
        LEFT JOIN curriculum_courses cc ON cc.curriculum_id = sp.curriculum_id AND cc.course_id = r.course_id
        LEFT JOIN curriculum_blocks b ON b.id = cc.block_id
        WHERE sp.is_primary
        GROUP BY sp.student_id, sp.id;
